// <auto-generated />
using Boyner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boyner.Core.Migrations
{
    [DbContext(typeof(ConfigContext))]
    [Migration("20190310194946_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Boyner.Domain.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Config");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationName = "SERVICE-A",
                            IsActive = true,
                            Name = "SiteName",
                            Type = "String",
                            Value = "Boyner.com.tr"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationName = "SERVICE-B",
                            IsActive = true,
                            Name = "IsBasketEnabled",
                            Type = "Boolean",
                            Value = "1"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationName = "SERVICE-A",
                            IsActive = false,
                            Name = "MaxItemCount",
                            Type = "Int",
                            Value = "50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
